use axum::{
    extract::{Request, State},
    http::header::AUTHORIZATION,
    middleware::Next,
    response::Response,
    routing::post,
    Extension, Json, Router,
};
use chrono::{Duration, Utc};
use jsonwebtoken::{decode, encode, DecodingKey, EncodingKey, Header, Validation};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::{
    api::AppState,
    db::models::User,
    error::{AppError, AppResult},
};

#[derive(Debug, Serialize, Deserialize)]
pub struct Claims {
    pub sub: String, // user id
    pub email: String,
    pub exp: i64,
    pub iat: i64,
}

#[derive(Debug, Deserialize)]
pub struct RegisterRequest {
    pub email: String,
    pub password: String,
    pub display_name: String,
}

#[derive(Debug, Deserialize)]
pub struct LoginRequest {
    pub email: String,
    pub password: String,
}

#[derive(Debug, Serialize)]
pub struct AuthResponse {
    pub access_token: String,
    pub refresh_token: String,
    pub token_type: String,
    /// Refresh-token lifetime in seconds. Frontend uses this to decide
    /// when to proactively rotate; the canonical authority is still the
    /// hash stored server-side.
    pub refresh_expires_in: i64,
    pub user: UserInfo,
}

#[derive(Debug, Deserialize)]
pub struct RefreshRequest {
    pub refresh_token: String,
}

#[derive(Debug, Serialize)]
pub struct RefreshResponse {
    pub access_token: String,
    pub refresh_token: String,
    pub token_type: String,
    pub refresh_expires_in: i64,
}

#[derive(Debug, Serialize)]
pub struct UserInfo {
    pub id: Uuid,
    pub email: String,
    pub display_name: String,
}

#[derive(Debug, Deserialize)]
struct ChangePasswordRequest {
    current_password: String,
    new_password: String,
}

// ── Route builders ────────────────────────────────────────────────────────────

pub fn public_routes() -> Router<AppState> {
    Router::new()
        .route("/auth/register", post(register))
        .route("/auth/login", post(login))
        .route("/auth/refresh", post(refresh))
        .route("/auth/logout", post(logout))
}

/// Routes that require an authenticated session (JWT via `require_auth`).
pub fn protected_routes() -> Router<AppState> {
    Router::new().route("/auth/change-password", post(change_password))
}

// ── Token helpers ─────────────────────────────────────────────────────────────

/// Generate a refresh token: 32 cryptographically random bytes encoded
/// as URL-safe base64. The server stores only the SHA-256 hash, so even
/// a DB leak doesn't expose live sessions.
fn generate_refresh_token() -> String {
    use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
    use rand::RngCore;
    let mut bytes = [0u8; 32];
    rand::thread_rng().fill_bytes(&mut bytes);
    URL_SAFE_NO_PAD.encode(bytes)
}

fn hash_refresh_token(token: &str) -> String {
    use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
    use sha2::{Digest, Sha256};
    let digest = Sha256::digest(token.as_bytes());
    URL_SAFE_NO_PAD.encode(digest)
}

/// Insert a refresh token row keyed by hash; returns the raw token.
async fn issue_refresh_token(state: &AppState, user_id: Uuid) -> AppResult<(String, i64)> {
    let raw = generate_refresh_token();
    let hash = hash_refresh_token(&raw);
    let ttl_days = state.config.refresh_token_expiry_days;
    let expires_at = Utc::now() + Duration::days(ttl_days);

    sqlx::query(
        "INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
         VALUES ($1, $2, $3)",
    )
    .bind(user_id)
    .bind(&hash)
    .bind(expires_at)
    .execute(&state.db)
    .await?;

    // Opportunistically prune expired rows for this user so the table
    // doesn't grow forever. Best-effort; ignore errors.
    let _ = sqlx::query(
        "DELETE FROM refresh_tokens
         WHERE user_id = $1 AND expires_at < NOW()",
    )
    .bind(user_id)
    .execute(&state.db)
    .await;

    Ok((raw, ttl_days * 86400))
}

// ── Handlers ──────────────────────────────────────────────────────────────────

async fn register(
    State(state): State<AppState>,
    Json(req): Json<RegisterRequest>,
) -> AppResult<Json<AuthResponse>> {
    if req.email.is_empty() || req.password.len() < 8 {
        return Err(AppError::BadRequest(
            "Email required and password must be at least 8 characters".into(),
        ));
    }

    let existing: Option<User> =
        sqlx::query_as("SELECT * FROM users WHERE email = $1")
            .bind(&req.email)
            .fetch_optional(&state.db)
            .await?;

    if existing.is_some() {
        return Err(AppError::BadRequest("Email already registered".into()));
    }

    // Hash password in a blocking thread (Argon2 is CPU-intensive).
    let password = req.password.clone();
    let password_hash = tokio::task::spawn_blocking(move || hash_password(&password))
        .await
        .map_err(|e| AppError::Internal(anyhow::anyhow!("spawn_blocking panic: {}", e)))??;

    // INSERT; kek_salt is generated by Postgres (gen_random_bytes in migration 0042).
    let user: User = sqlx::query_as(
        "INSERT INTO users (email, password_hash, display_name)
         VALUES ($1, $2, $3)
         RETURNING *",
    )
    .bind(&req.email)
    .bind(&password_hash)
    .bind(&req.display_name)
    .fetch_one(&state.db)
    .await?;

    // Derive the User KEK from the plaintext password + the DB-generated salt.
    // Do this in spawn_blocking: Argon2id at 64 MiB takes ~200 ms.
    let pw2 = req.password.clone();
    let salt = user.kek_salt.clone();
    let kek = tokio::task::spawn_blocking(move || {
        crate::security::vault_crypto::derive_user_kek(&pw2, &salt)
            .map_err(|e| AppError::Internal(anyhow::anyhow!("KEK derive: {}", e)))
    })
    .await
    .map_err(|e| AppError::Internal(anyhow::anyhow!("spawn_blocking panic: {}", e)))??;

    state.session_keys.insert(user.id, kek);

    let access =
        generate_token(&user, &state.config.jwt_secret, state.config.jwt_expiry_hours)?;
    let (refresh_token, refresh_expires_in) = issue_refresh_token(&state, user.id).await?;

    Ok(Json(AuthResponse {
        access_token: access,
        refresh_token,
        token_type: "Bearer".into(),
        refresh_expires_in,
        user: UserInfo {
            id: user.id,
            email: user.email,
            display_name: user.display_name,
        },
    }))
}

async fn login(
    State(state): State<AppState>,
    Json(req): Json<LoginRequest>,
) -> AppResult<Json<AuthResponse>> {
    let user: Option<User> = sqlx::query_as("SELECT * FROM users WHERE email = $1")
        .bind(&req.email)
        .fetch_optional(&state.db)
        .await?;

    let user = user.ok_or_else(|| AppError::Unauthorized("Invalid credentials".into()))?;

    // Batch verify_password + derive_user_kek in a single blocking thread:
    // both are Argon2 operations (~200 ms each); batching avoids two thread-pool
    // round-trips and makes the total login latency predictable (~400 ms).
    let password = req.password.clone();
    let pw_hash = user.password_hash.clone();
    let kek_salt = user.kek_salt.clone();

    let (verified, maybe_kek) = tokio::task::spawn_blocking(move || {
        let ok = verify_password(&password, &pw_hash)?;
        if !ok {
            return Ok::<(bool, Option<[u8; 32]>), AppError>((false, None));
        }
        let kek = crate::security::vault_crypto::derive_user_kek(&password, &kek_salt)
            .map_err(|e| AppError::Internal(anyhow::anyhow!("KEK derive: {}", e)))?;
        Ok((true, Some(kek)))
    })
    .await
    .map_err(|e| AppError::Internal(anyhow::anyhow!("spawn_blocking panic: {}", e)))??;

    if !verified {
        return Err(AppError::Unauthorized("Invalid credentials".into()));
    }

    if let Some(kek) = maybe_kek {
        state.session_keys.insert(user.id, kek);
    }

    let access =
        generate_token(&user, &state.config.jwt_secret, state.config.jwt_expiry_hours)?;
    let (refresh_token, refresh_expires_in) = issue_refresh_token(&state, user.id).await?;

    Ok(Json(AuthResponse {
        access_token: access,
        refresh_token,
        token_type: "Bearer".into(),
        refresh_expires_in,
        user: UserInfo {
            id: user.id,
            email: user.email,
            display_name: user.display_name,
        },
    }))
}

async fn refresh(
    State(state): State<AppState>,
    Json(req): Json<RefreshRequest>,
) -> AppResult<Json<RefreshResponse>> {
    let hash = hash_refresh_token(&req.refresh_token);

    // Atomically delete the presented refresh token and capture its
    // user_id only if it's not expired. This implements *rotation*:
    // each refresh consumes the old token, so a leaked token is one-use.
    let row: Option<(Uuid,)> = sqlx::query_as(
        "DELETE FROM refresh_tokens
         WHERE token_hash = $1 AND expires_at > NOW()
         RETURNING user_id",
    )
    .bind(&hash)
    .fetch_optional(&state.db)
    .await?;
    let user_id = row
        .ok_or_else(|| AppError::Unauthorized("Invalid or expired refresh token".into()))?
        .0;

    let user: User = sqlx::query_as("SELECT * FROM users WHERE id = $1")
        .bind(user_id)
        .fetch_optional(&state.db)
        .await?
        .ok_or_else(|| AppError::Unauthorized("User no longer exists".into()))?;

    // Extend the in-RAM User KEK TTL so active users don't need to log in
    // again just because their session key expired mid-session.
    state.session_keys.refresh(user_id);

    let access =
        generate_token(&user, &state.config.jwt_secret, state.config.jwt_expiry_hours)?;
    let (refresh_token, refresh_expires_in) = issue_refresh_token(&state, user.id).await?;

    Ok(Json(RefreshResponse {
        access_token: access,
        refresh_token,
        token_type: "Bearer".into(),
        refresh_expires_in,
    }))
}

async fn logout(
    State(state): State<AppState>,
    Json(req): Json<RefreshRequest>,
) -> AppResult<axum::http::StatusCode> {
    let hash = hash_refresh_token(&req.refresh_token);

    // Use RETURNING to get the user_id so we can evict the in-RAM User KEK.
    // If the token was already expired/missing this is a no-op (None).
    let row: Option<(Uuid,)> = sqlx::query_as(
        "DELETE FROM refresh_tokens WHERE token_hash = $1 RETURNING user_id",
    )
    .bind(&hash)
    .fetch_optional(&state.db)
    .await
    .unwrap_or(None);

    if let Some((user_id,)) = row {
        // Zeroizes the 32-byte KEK in RAM via SessionEntry::Drop.
        state.session_keys.remove(user_id);
    }

    Ok(axum::http::StatusCode::NO_CONTENT)
}

/// Change password: verify old → derive old KEK → derive new KEK → re-wrap all
/// user-keyed DEKs in one transaction → update password_hash → refresh session.
///
/// The System KEK wrappings are untouched: they always point to the same DEK
/// bytes regardless of what user password wraps the user's copy.
async fn change_password(
    State(state): State<AppState>,
    Extension(auth_user): Extension<AuthUser>,
    Json(req): Json<ChangePasswordRequest>,
) -> AppResult<axum::http::StatusCode> {
    if req.new_password.len() < 8 {
        return Err(AppError::BadRequest(
            "New password must be at least 8 characters".into(),
        ));
    }

    let user: User = sqlx::query_as("SELECT * FROM users WHERE id = $1")
        .bind(auth_user.id)
        .fetch_optional(&state.db)
        .await?
        .ok_or_else(|| AppError::Unauthorized("User not found".into()))?;

    // All three Argon2 operations (verify + 2× derive) batched into one
    // blocking thread to minimise async thread-pool overhead.
    let cur_pw = req.current_password.clone();
    let new_pw = req.new_password.clone();
    let pw_hash = user.password_hash.clone();
    let kek_salt = user.kek_salt.clone();

    let result = tokio::task::spawn_blocking(move || {
        let ok = verify_password(&cur_pw, &pw_hash)?;
        if !ok {
            return Ok::<Option<([u8; 32], [u8; 32], String)>, AppError>(None);
        }

        let old_kek = crate::security::vault_crypto::derive_user_kek(&cur_pw, &kek_salt)
            .map_err(|e| AppError::Internal(anyhow::anyhow!("old KEK derive: {}", e)))?;
        let new_kek = crate::security::vault_crypto::derive_user_kek(&new_pw, &kek_salt)
            .map_err(|e| AppError::Internal(anyhow::anyhow!("new KEK derive: {}", e)))?;
        let new_hash = hash_password(&new_pw)?;

        Ok(Some((old_kek, new_kek, new_hash)))
    })
    .await
    .map_err(|e| AppError::Internal(anyhow::anyhow!("spawn_blocking panic: {}", e)))??;

    let (old_kek, new_kek, new_hash) = result
        .ok_or_else(|| AppError::Unauthorized("Current password is incorrect".into()))?;

    // Re-wrap DEKs and update password_hash in a single transaction.
    re_wrap_deks_and_update_password(
        &state.db,
        auth_user.id,
        &old_kek,
        &new_kek,
        &new_hash,
    )
    .await?;

    // Replace the in-RAM User KEK with the new one.
    state.session_keys.insert(auth_user.id, new_kek);

    Ok(axum::http::StatusCode::NO_CONTENT)
}

/// Re-wrap every `vault_key_wrappings` row keyed by `user:{id}` from the old
/// User KEK to the new one, then update `users.password_hash` — all in one
/// atomic transaction so a crash mid-flight leaves the DB consistent.
async fn re_wrap_deks_and_update_password(
    db: &sqlx::PgPool,
    user_id: Uuid,
    old_kek: &[u8; 32],
    new_kek: &[u8; 32],
    new_hash: &str,
) -> AppResult<()> {
    use crate::crypto::TokenCipher;
    use crate::security::vault_crypto::{unwrap_dek, wrap_dek};

    let old_cipher = TokenCipher::from_raw_key(old_kek);
    let new_cipher = TokenCipher::from_raw_key(new_kek);
    let alias = format!("user:{}", user_id);

    let mut tx = db.begin().await?;

    // Lock all matching rows for the duration of the transaction.
    let rows: Vec<(Uuid, String)> = sqlx::query_as(
        "SELECT object_id, wrapped_dek
         FROM vault_key_wrappings
         WHERE kek_alias = $1
         FOR UPDATE",
    )
    .bind(&alias)
    .fetch_all(&mut *tx)
    .await?;

    for (object_id, wrapped_dek) in rows {
        let dek = unwrap_dek(&old_cipher, &wrapped_dek)
            .map_err(|e| AppError::Internal(anyhow::anyhow!("re-wrap unwrap object_id={}: {}", object_id, e)))?;
        let new_wrapped = wrap_dek(&new_cipher, &dek)
            .map_err(|e| AppError::Internal(anyhow::anyhow!("re-wrap wrap object_id={}: {}", object_id, e)))?;

        sqlx::query(
            "UPDATE vault_key_wrappings
             SET wrapped_dek = $1
             WHERE object_id = $2 AND kek_alias = $3",
        )
        .bind(&new_wrapped)
        .bind(object_id)
        .bind(&alias)
        .execute(&mut *tx)
        .await?;
    }

    // Update the password hash atomically with the DEK re-wrapping.
    sqlx::query("UPDATE users SET password_hash = $1 WHERE id = $2")
        .bind(new_hash)
        .bind(user_id)
        .execute(&mut *tx)
        .await?;

    tx.commit().await?;
    Ok(())
}

// ── Low-level crypto helpers ──────────────────────────────────────────────────

pub fn generate_token(user: &User, secret: &str, expiry_hours: i64) -> AppResult<String> {
    let now = Utc::now();
    let claims = Claims {
        sub: user.id.to_string(),
        email: user.email.clone(),
        exp: (now + Duration::hours(expiry_hours)).timestamp(),
        iat: now.timestamp(),
    };
    encode(
        &Header::default(),
        &claims,
        &EncodingKey::from_secret(secret.as_bytes()),
    )
    .map_err(|e| AppError::Internal(anyhow::anyhow!("JWT encode error: {}", e)))
}

pub fn verify_token(token: &str, secret: &str) -> AppResult<Claims> {
    decode::<Claims>(
        token,
        &DecodingKey::from_secret(secret.as_bytes()),
        &Validation::default(),
    )
    .map(|data| data.claims)
    .map_err(|_| AppError::Unauthorized("Invalid or expired token".into()))
}

fn hash_password(password: &str) -> AppResult<String> {
    use argon2::{
        password_hash::{rand_core::OsRng, PasswordHasher, SaltString},
        Argon2,
    };
    let salt = SaltString::generate(&mut OsRng);
    Argon2::default()
        .hash_password(password.as_bytes(), &salt)
        .map(|h| h.to_string())
        .map_err(|e| AppError::Internal(anyhow::anyhow!("Password hash error: {}", e)))
}

fn verify_password(password: &str, hash: &str) -> AppResult<bool> {
    use argon2::{
        password_hash::{PasswordHash, PasswordVerifier},
        Argon2,
    };
    let parsed = PasswordHash::new(hash)
        .map_err(|e| AppError::Internal(anyhow::anyhow!("Hash parse error: {}", e)))?;
    Ok(Argon2::default()
        .verify_password(password.as_bytes(), &parsed)
        .is_ok())
}

// ── Auth middleware ───────────────────────────────────────────────────────────

#[derive(Clone, Debug)]
pub struct AuthUser {
    pub id: Uuid,
    #[allow(dead_code)]
    pub email: String,
}

pub async fn require_auth(
    State(state): State<AppState>,
    mut req: Request,
    next: Next,
) -> Result<Response, AppError> {
    let token = req
        .headers()
        .get(AUTHORIZATION)
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.strip_prefix("Bearer "))
        .ok_or_else(|| AppError::Unauthorized("Missing authorization header".into()))?;

    let claims = verify_token(token, &state.config.jwt_secret)?;
    let user_id = Uuid::parse_str(&claims.sub)
        .map_err(|_| AppError::Unauthorized("Invalid token subject".into()))?;

    req.extensions_mut().insert(AuthUser {
        id: user_id,
        email: claims.email,
    });

    Ok(next.run(req).await)
}
